export const theme = {
  colors: {
    primary: '#D4522A',
    primaryLight: '#E8845A',
    primaryDark: '#A83D1E',
    secondary: '#E8A020',
    background: '#F0EBE3',
    surface: '#EAE4DC',
    surfaceElevated: '#FFFFFF',
    card: '#E8DDD3',
    text: '#2C1810',
    textSecondary: '#6B4226',
    textMuted: '#A0714F',
    border: '#D4C4B4',
    success: '#5A8A4A',
    error: '#C0392B',
    veg: '#5A8A4A',
    nonVeg: '#C0392B',
    vegan: '#7A9A3A',
    white: '#FFFFFF',
    black: '#000000',
  },
  fonts: {
    regular: 'System',
    medium: 'System',
    bold: 'System',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 999,
  },
  shadow: {
    small: {
      shadowColor: '#8B4513',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    medium: {
      shadowColor: '#8B4513',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 6,
    },
  },
};